### ISSUE TITLE
repomd.xml signature could not be verified for virtualbox

### ISSUE THREAD

**Issue by DigitalGlobeEricDuvic** [andrewrothstein/ansible-virtualbox#1]
Hi, I am attempting to use your role to install virtualbox on a Centos7 VM via Vagrant. However, I get the following error:

> TASK [andrewrothstein.virtualbox : install virtualbox] *************************
fatal: [default]: FAILED! => {"changed": false, "msg": "Failure talking to yum: failure: repodata/repomd.xml from virtualbox: [Errno 256] No more mirrors to try.\nhttp://download.virtualbox.org/virtualbox/rpm/el/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for virtualbox"}

Please let me know if there's something that I am missing. Thanks!

**Comment by DigitalGlobeEricDuvic** [comment]
Trying a manual install:
> sudo yum install -y VirtualBox-5.2

I get the following prompt:
> Retrieving key from https://www.virtualbox.org/download/oracle_vbox.asc
Importing GPG key 0x98AB5139:
 Userid     : "Oracle Corporation (VirtualBox archive signing key) <info@virtualbox.org>"
 Fingerprint: 7b0f ab3a 13b9 0743 5925 d9c9 5442 2a4b 98ab 5139
 From       : https://www.virtualbox.org/download/oracle_vbox.asc
Is this ok [y/N]: y

Answering `y` installs VirtualBox without issue.

I've even attempted to run an ansible `pre_task` to install the gpg key:
>   pre_tasks:
>   - name: Add GPG key for virtualbox
>     rpm_key:
>       key: https://www.virtualbox.org/download/oracle_vbox.asc

**Comment by andrewrothstein** [comment]
Why are you trying to install VirtualBox within a VM?

**Comment by DigitalGlobeEricDuvic** [comment]
Andrew, I'm attempting to set up an automated, reusable environment for testing Ansible roles with Molecule.

**Comment by andrewrothstein** [comment]
can you share a simple example of your vagrant setup? You're absolutely sure you want to nest VMs?

**Comment by DigitalGlobeEricDuvic** [comment]
@andrewrothstein you can find an example here: https://github.com/DigitalGlobeEricDuvic/ansible-virtualbox-example

And yes, I'm absolutely sure I want to nest VMs
![We need to go deeper](https://i.imgur.com/BvuWRxq.jpg)

**Comment by andrewrothstein** [comment]
per https://github.com/ansible/ansible/issues/20711 the rpm_key task doesn't do the full deed in terms of blessing the key. I followed the work around and published as v1.1.1 to the galaxy. Thanks for pointing this out!
